export const initialData = {
  company: {
    name: "PLATAFORMAPARK",
    platform: "PLATAFORMA PARK CMMS",
    subtitle: "Sistema de Mantenimiento de Infraestructura & Parques Industriales",
    logoText: "PARK",
    groupText: "PLATAFORMAPARK",
    contactEmail: "mantenimiento@plataformapark.com",
    phone: "+52 (33) 3800-PARK",
    address: "Av. Paseo Royal #500, Corporativo PlataformaPark"
  },
  assets: [
    {
      id: "AST-101",
      code: "PARK-EQ-501",
      name: "Subestación Eléctrica Principal 500kVA",
      category: "Eléctrico",
      location: "Park Industrial Guadalajara - Edificio A",
      development: "Park Industrial Guadalajara",
      brand: "Schneider Electric",
      model: "Trihal 500kVA 23kV/480V",
      serialNumber: "SE-2023-8891-GF",
      status: "Operativo",
      criticality: "Alta",
      installationDate: "2022-03-15",
      mttrHours: 2.5,
      mtbfDays: 120,
      totalMaintenanceCost: 1450.00,
      specs: "Transformador seco encapsulado 500 kVA, Gabinete NEMA 3R, Interruptor principal de 800A."
    },
    {
      id: "AST-102",
      code: "PARK-EQ-102",
      name: "Sistema Chiller Central HVAC 120 TR",
      category: "Climatización / HVAC",
      location: "Park Plaza Ejecutiva - Azotea",
      development: "Park Plaza Ejecutiva",
      brand: "Carrier",
      model: "AquaSnap 30RB120",
      serialNumber: "CAR-30RB-99412",
      status: "En Mantenimiento",
      criticality: "Alta",
      installationDate: "2021-08-10",
      mttrHours: 4.0,
      mtbfDays: 65,
      totalMaintenanceCost: 3280.00,
      specs: "Enfriador de agua por aire con refrigerante R-410A, 2 circuitos independientes, compresores Scroll."
    },
    {
      id: "AST-103",
      code: "PARK-EQ-204",
      name: "Elevador Panorámico de Pasajeros #02",
      category: "Electromecánico",
      location: "Park Royal Residencial - Torre 1",
      development: "Park Royal Residencial",
      brand: "Otis",
      model: "Gen2 Comfort 1000kg",
      serialNumber: "OTIS-G2-77319",
      status: "Fuera de Servicio",
      criticality: "Alta",
      installationDate: "2023-01-20",
      mttrHours: 6.0,
      mtbfDays: 45,
      totalMaintenanceCost: 4120.00,
      specs: "Capacidad 13 pasajeros (1000 kg), 15 paradas, velocidad 1.75 m/s, cintas planas de acero recubiertas de poliuretano."
    },
    {
      id: "AST-104",
      code: "PARK-EQ-305",
      name: "Planta de Luz de Emergencia 250 kW",
      category: "Generación Power",
      location: "Park Logistics Hub - Nave 3",
      development: "Park Logistics Hub",
      brand: "Caterpillar",
      model: "DE250E0 250kW Diésel",
      serialNumber: "CAT-C9-44120-GF",
      status: "Operativo",
      criticality: "Alta",
      installationDate: "2022-11-05",
      mttrHours: 1.8,
      mtbfDays: 180,
      totalMaintenanceCost: 890.00,
      specs: "Motor Cat C9 ACERT, Tanque de combustible base 500L, Caseta acustizada 75 dBA @ 7m."
    },
    {
      id: "AST-105",
      code: "PARK-EQ-408",
      name: "Sistema Contra Incendio Bombeo Central",
      category: "Hidrosanitario & Seguridad",
      location: "Park Industrial Guadalajara - Cuarto de Bombas",
      development: "Park Industrial Guadalajara",
      brand: "Grundfos",
      model: "Hydro MPC-E 3 CR64-2",
      serialNumber: "GRU-PCI-88301",
      status: "Operativo",
      criticality: "Alta",
      installationDate: "2020-05-18",
      mttrHours: 3.0,
      mtbfDays: 90,
      totalMaintenanceCost: 2150.00,
      specs: "Bomba principal diésel 75 HP + Bomba eléctrica 75 HP + Bomba Jockey 5 HP. Caudal 1000 GPM @ 125 PSI."
    },
    {
      id: "AST-106",
      code: "PARK-EQ-612",
      name: "Portón Automatizado Heavy Duty Acceso Sur",
      category: "Control de Acceso",
      location: "Park Logistics Hub - Caseta 1",
      development: "Park Logistics Hub",
      brand: "FAAC",
      model: "844 ER 3PH 1800kg",
      serialNumber: "FAAC-844-00291",
      status: "Operativo",
      criticality: "Media",
      installationDate: "2023-04-12",
      mttrHours: 1.2,
      mtbfDays: 75,
      totalMaintenanceCost: 430.00,
      specs: "Motorreductor en baño de aceite, embrague bidisco de seguridad, frecuencia de uso industrial 100%."
    }
  ],
  workOrders: [
    {
      id: "WO-8041",
      code: "WO-8041",
      title: "Inspección Trimestral Termográfica y Ajuste de Subestación 500kVA",
      description: "Realizar inspección termográfica de conexiones de alta y baja tensión, apretar par de apriete en bornes, limpiar aisladores y verificar puesta a tierra.",
      priority: "Media",
      status: "Completada",
      category: "Preventivo",
      assetId: "AST-101",
      assetName: "Subestación Eléctrica Principal 500kVA",
      development: "Park Industrial Guadalajara",
      location: "Edificio A - Cuarto Eléctrico Principal",
      assignedTech: "Ing. Carlos Mendoza",
      assignedTechRole: "Técnico Senior Eléctrico",
      createdDate: "2026-07-15T09:00:00",
      dueDate: "2026-07-20T18:00:00",
      completedDate: "2026-07-19T14:30:00",
      estimatedHours: 3.5,
      actualHours: 3.0,
      checklist: [
        { id: 1, text: "Verificar ausencias de tensión y colocar bloqueo LOTO de seguridad.", completed: true, timestamp: "2026-07-19 09:15" },
        { id: 2, text: "Escanear termográficamente clemas y transformador en carga.", completed: true, timestamp: "2026-07-19 10:00" },
        { id: 3, text: "Limpiar polvo acumulado en aletas con aire seco a presión.", completed: true, timestamp: "2026-07-19 11:20" },
        { id: 4, text: "Torquear tornillería a 45 Nm según especificación de fabricante.", completed: true, timestamp: "2026-07-19 12:45" },
        { id: 5, text: "Prueba de continuidad de tierra y reapertura de interruptor.", completed: true, timestamp: "2026-07-19 14:10" }
      ],
      usedParts: [
        { partId: "PRT-004", name: "Fusible de Alta Tensión 100A 15kV", qty: 1, unitCost: 120.00, totalCost: 120.00 },
        { partId: "PRT-008", name: "Limpiador Dieléctrico de Contactos 500ml", qty: 2, unitCost: 18.50, totalCost: 37.00 }
      ],
      totalPartsCost: 157.00,
      totalLaborCost: 180.00,
      grandTotal: 337.00,
      technicianNotes: "Mantenimiento realizado satisfactoriamente. Se detectó ligera sobretemperatura en fase B antes del torqueo, resuelto al ajustar tornillo suelto. Parámetros normales.",
      signatureData: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='200' height='60'><path d='M 10 40 Q 30 10 60 40 T 120 30 T 180 50' stroke='%238CC63F' stroke-width='3' fill='none'/><text x='10' y='55' fill='%2394A3B8' font-size='10'>Firma: C. Mendoza</text></svg>",
      comments: [
        {
          id: "cmt-1",
          userId: "u-admin-001",
          userName: "Ing. Carlos Mendoza",
          userRole: "admin",
          roleBadge: "bg-blue-100 text-blue-800",
          avatarColor: "bg-[#0A3963]",
          timestamp: "2026-07-19 09:10",
          text: "Iniciando labores en subestación. Candados LOTO colocados.",
          type: "comment"
        },
        {
          id: "cmt-2",
          userId: "u-admin-001",
          userName: "Ing. Carlos Mendoza",
          userRole: "admin",
          roleBadge: "bg-blue-100 text-blue-800",
          avatarColor: "bg-[#0A3963]",
          timestamp: "2026-07-19 14:25",
          text: "Inspección completada con éxito. Equipo en servicio normal.",
          type: "comment"
        }
      ]
    },
    {
      id: "WO-8042",
      code: "WO-8042",
      title: "Reemplazo de Filtros y Lubricación General de Chiller Carrier",
      description: "Sustitución de filtros de aire de condensadores, verificación de presión de gas R-410A, lubricación de rodamientos de ventilador axial y purga de aceite.",
      priority: "Alta",
      status: "En Proceso",
      category: "Preventivo",
      assetId: "AST-102",
      assetName: "Sistema Chiller Central HVAC 120 TR",
      development: "Park Plaza Ejecutiva",
      location: "Azotea - Área de Enfriadores",
      assignedTech: "Téc. Roberto Gómez",
      assignedTechRole: "Especialista HVAC",
      createdDate: "2026-07-25T10:30:00",
      dueDate: "2026-07-30T17:00:00",
      completedDate: null,
      estimatedHours: 5.0,
      actualHours: 2.5,
      checklist: [
        { id: 1, text: "Apagar unidad Chiller desde BMS de la plaza.", completed: true, timestamp: "2026-07-28 08:30" },
        { id: 2, text: "Retirar filtros MERV 13 saturados y colocar repuestos nuevos.", completed: true, timestamp: "2026-07-28 10:15" },
        { id: 3, text: "Medir presiones de succión y descarga en circuitos 1 y 2.", completed: true, timestamp: "2026-07-28 11:45" },
        { id: 4, text: "Lubricar chumaceras de ventiladores axiales con grasa de litio.", completed: false, timestamp: null },
        { id: 5, text: "Revisar alineación de poleas y tensión de correas.", completed: false, timestamp: null }
      ],
      usedParts: [
        { partId: "PRT-001", name: "Filtro de Aire HVAC 24x24x2 MERV 13", qty: 4, unitCost: 45.00, totalCost: 180.00 },
        { partId: "PRT-002", name: "Aceite Sintético para Compresor Garrafa 20L", qty: 1, unitCost: 185.00, totalCost: 185.00 }
      ],
      totalPartsCost: 365.00,
      totalLaborCost: 250.00,
      grandTotal: 615.00,
      technicianNotes: "Filtros colocados. Avance del 60%. Mañana se concluye lubricación de chumaceras.",
      signatureData: null,
      comments: [
        {
          id: "cmt-3",
          userId: "u-auditor-005",
          userName: "Téc. Roberto Gómez",
          userRole: "tecnico",
          roleBadge: "bg-emerald-100 text-emerald-800",
          avatarColor: "bg-emerald-600",
          timestamp: "2026-07-28 10:20",
          text: "Filtros reemplazados con éxito. Presiones de refrigerante en rango estándar.",
          type: "comment"
        }
      ]
    },
    {
      id: "WO-8043",
      code: "WO-8043",
      title: "Reparación Urgente: Elevador Otis #02 Fuera de Servicio",
      description: "El elevador se bloqueó en el piso 8 debido a falla en cortina infrarroja de fotocelda de seguridad de puertas. Residentes sin acceso panorámico.",
      priority: "Urgente",
      status: "Abierta",
      category: "Correctivo",
      assetId: "AST-103",
      assetName: "Elevador Panorámico de Pasajeros #02",
      development: "Park Royal Residencial",
      location: "Torre 1 - Piso 8",
      assignedTech: "Téc. Juan Pérez",
      assignedTechEmail: "tecnico@park.com",
      assignedTechRole: "Especialista Elevación Otis",
      createdDate: "2026-07-29T08:15:00",
      dueDate: "2026-07-29T14:00:00",
      completedDate: null,
      estimatedHours: 2.0,
      actualHours: 0.0,
      checklist: [
        { id: 1, text: "Intervenir fosa y cabina con señalética de Fuera de Servicio.", completed: false, timestamp: null },
        { id: 2, text: "Diagnosticar código de falla en cuadro de control OTIS Gen2.", completed: false, timestamp: null },
        { id: 3, text: "Reemplazar sensor fotoeléctrico de la puerta de cabina.", completed: false, timestamp: null },
        { id: 4, text: "Realizar 10 viajes de prueba de apertura/cierre de puertas.", completed: false, timestamp: null }
      ],
      usedParts: [
        { partId: "PRT-005", name: "Sensor Fotoeléctrico de Presencia Omron", qty: 1, unitCost: 85.00, totalCost: 85.00 }
      ],
      totalPartsCost: 85.00,
      totalLaborCost: 160.00,
      grandTotal: 245.00,
      technicianNotes: "Atención inmediata requerida. Refacción en ruta con el técnico.",
      signatureData: null,
      comments: []
    },
    {
      id: "WO-8044",
      code: "WO-8044",
      title: "Prueba Operativa en Vacío y Con Carga - Planta Caterpillar 250kW",
      description: "Arranque mensual de prueba de la planta de emergencia diésel, verificación de transferencia automática (ATS), nivel de electrolito y presión de aceite.",
      priority: "Media",
      status: "Abierta",
      category: "Preventivo",
      assetId: "AST-104",
      assetName: "Planta de Luz de Emergencia 250 kW",
      development: "Park Logistics Hub",
      location: "Nave 3 - Caseta de Generador",
      assignedTech: "Téc. Fernando Ruiz",
      assignedTechRole: "Técnico Electromecánico",
      createdDate: "2026-07-27T11:00:00",
      dueDate: "2026-07-31T12:00:00",
      completedDate: null,
      estimatedHours: 2.0,
      actualHours: 0.0,
      checklist: [
        { id: 1, text: "Inspeccionar nivel de combustible diésel y refrigerante.", completed: false, timestamp: null },
        { id: 2, text: "Verificar voltaje de batería de arranque (mínimo 24.5V CD).", completed: false, timestamp: null },
        { id: 3, text: "Arrancar en modo Manual durante 15 minutos sin carga.", completed: false, timestamp: null },
        { id: 4, text: "Simular corte de suministro en ATS y verificar conmutación a los 8 segundos.", completed: false, timestamp: null }
      ],
      usedParts: [],
      totalPartsCost: 0.00,
      totalLaborCost: 100.00,
      grandTotal: 100.00,
      technicianNotes: "Programado para viernes a mediodía.",
      signatureData: null,
      comments: []
    },
    {
      id: "WO-8045",
      code: "WO-8045",
      title: "Calibración de Presostatos y Prueba de Válvulas PCI Grundfos",
      description: "Ajuste de puntos de arranque de bomba Jockey y bomba principal contra incendios. Pruebas de estanqueidad de tuberías.",
      priority: "Baja",
      status: "En Espera",
      category: "Inspección",
      assetId: "AST-105",
      assetName: "Sistema Contra Incendio Bombeo Central",
      development: "Park Industrial Guadalajara",
      location: "Cuarto de Bombas",
      assignedTech: "Ing. Carlos Mendoza",
      assignedTechRole: "Técnico Senior Eléctrico",
      createdDate: "2026-07-26T14:00:00",
      dueDate: "2026-08-02T17:00:00",
      completedDate: null,
      estimatedHours: 4.0,
      actualHours: 0.0,
      checklist: [
        { id: 1, text: "Drenar manómetro de prueba y verificar manómetros patrones.", completed: false, timestamp: null },
        { id: 2, text: "Ajustar presostato Jockey a 130 PSI disparo / 145 PSI paro.", completed: false, timestamp: null },
        { id: 3, text: "Probar disparo de bomba diésel principal por caída de presión.", completed: false, timestamp: null }
      ],
      usedParts: [],
      totalPartsCost: 0.00,
      totalLaborCost: 200.00,
      grandTotal: 200.00,
      technicianNotes: "En espera de llegada de manómetro digital de calibración externa.",
      signatureData: null,
      comments: []
    },
    {
      id: "WO-8046",
      code: "WO-8046",
      title: "Inspección y Ajuste de Portón Automatizado Acceso Sur",
      description: "Revisar fotoceldas de seguridad, engrasar cremallera y verificar embrague de seguridad de portón industrial FAAC.",
      priority: "Alta",
      status: "Abierta",
      category: "Preventivo",
      assetId: "AST-106",
      assetName: "Portón Automatizado Heavy Duty Acceso Sur",
      development: "Park Logistics Hub",
      location: "Park Logistics Hub - Caseta 1",
      assignedTech: "Téc. Juan Pérez",
      assignedTechEmail: "tecnico@park.com",
      assignedTechRole: "Mantenimiento Operativo",
      createdDate: "2026-09-15T09:00:00",
      dueDate: "2026-09-16T18:00:00",
      completedDate: null,
      estimatedHours: 2.5,
      actualHours: 0.0,
      checklist: [
        { id: 1, text: "Inspeccionar estado de fotoceldas y reflectores infrarrojos.", completed: false, timestamp: null },
        { id: 2, text: "Limpiar y engrasar cremallera y piñón de ataque.", completed: false, timestamp: null },
        { id: 3, text: "Probar inversión de marcha anti-aplastamiento.", completed: false, timestamp: null }
      ],
      usedParts: [
        { partId: "PRT-008", name: "Limpiador Dieléctrico de Contactos 500ml", qty: 1, unitCost: 18.50, totalCost: 18.50 }
      ],
      totalPartsCost: 18.50,
      totalLaborCost: 125.00,
      grandTotal: 143.50,
      technicianNotes: "Prioridad operativa para flujo de camiones pesados.",
      signatureData: null,
      comments: []
    }
  ],
  inventory: [
    {
      id: "PRT-001",
      sku: "FIL-HVAC-2424",
      name: "Filtro de Aire HVAC 24x24x2 MERV 13",
      category: "Climatización",
      currentStock: 4,
      minStock: 8,
      unitCost: 45.00,
      unit: "Pieza",
      supplier: "Filtros Industriales de México S.A.",
      location: "Almacén Central - RACK A-2"
    },
    {
      id: "PRT-002",
      sku: "OIL-SYN-68L",
      name: "Aceite Sintético para Compresor Garrafa 20L",
      category: "Lubricantes",
      currentStock: 6,
      minStock: 3,
      unitCost: 185.00,
      unit: "Garrafa",
      supplier: "Mobil Industrial Lubricants",
      location: "Almacén Químicos - Estante B"
    },
    {
      id: "PRT-003",
      sku: "ROD-SKF-6208",
      name: "Rodamiento Industrial SKF 6208 2RS",
      category: "Mecánica",
      currentStock: 12,
      minStock: 5,
      unitCost: 32.00,
      unit: "Pieza",
      supplier: "Rodamientos y Bandas del Pacífico",
      location: "Almacén Central - RACK C-1"
    },
    {
      id: "PRT-004",
      sku: "FUS-HV-100A",
      name: "Fusible de Alta Tensión 100A 15kV",
      category: "Eléctrico",
      currentStock: 2,
      minStock: 4,
      unitCost: 120.00,
      unit: "Pieza",
      supplier: "Eléctrica Industrial PlataformaPark",
      location: "Almacén Eléctrico - Gabinete 3"
    },
    {
      id: "PRT-005",
      sku: "SEN-OMR-E3Z",
      name: "Sensor Fotoeléctrico de Presencia Omron",
      category: "Automatización",
      currentStock: 1,
      minStock: 3,
      unitCost: 85.00,
      unit: "Pieza",
      supplier: "Omron Automation Mexico",
      location: "Almacén Electrónico - Cajón D"
    },
    {
      id: "PRT-006",
      sku: "BAN-GAT-B85",
      name: "Banda de Transmisión Industrial Gates V-Belt B-85",
      category: "Mecánica",
      currentStock: 15,
      minStock: 6,
      unitCost: 28.00,
      unit: "Pieza",
      supplier: "Gates de México",
      location: "Almacén Central - RACK C-3"
    },
    {
      id: "PRT-007",
      sku: "BAT-CTP-100",
      name: "Batería CTP 12V 100Ah para Planta Diésel",
      category: "Generación",
      currentStock: 3,
      minStock: 2,
      unitCost: 210.00,
      unit: "Pieza",
      supplier: "Acumuladores Industriales",
      location: "Almacén Planta Baja"
    },
    {
      id: "PRT-008",
      sku: "QUIM-DIE-500",
      name: "Limpiador Dieléctrico de Contactos 500ml",
      category: "Químicos",
      currentStock: 18,
      minStock: 5,
      unitCost: 18.50,
      unit: "Lata Spray",
      supplier: "CRC Industries",
      location: "Almacén Químicos"
    }
  ],
  preventiveSchedules: [
    {
      id: "PM-101",
      title: "Mantenimiento Preventivo Trimestral de Subestación 500kVA",
      assetId: "AST-101",
      assetName: "Subestación Eléctrica Principal 500kVA",
      frequency: "Trimestral",
      nextDueDate: "2026-10-15",
      assignedTech: "Ing. Carlos Mendoza",
      estimatedHours: 4.0,
      active: true
    },
    {
      id: "PM-102",
      title: "Revisión Mensual de Chiller Carrier 120 TR",
      assetId: "AST-102",
      assetName: "Sistema Chiller Central HVAC 120 TR",
      frequency: "Mensual",
      nextDueDate: "2026-08-25",
      assignedTech: "Téc. Roberto Gómez",
      estimatedHours: 5.0,
      active: true
    },
    {
      id: "PM-103",
      title: "Mantenimiento Semanal de Elevador Otis #02",
      assetId: "AST-103",
      assetName: "Elevador Panorámico de Pasajeros #02",
      frequency: "Semanal",
      nextDueDate: "2026-08-03",
      assignedTech: "Téc. Juan Pérez",
      estimatedHours: 2.0,
      active: true
    },
    {
      id: "PM-104",
      title: "Arranque de Prueba Mensual Planta Diésel Caterpillar",
      assetId: "AST-104",
      assetName: "Planta de Luz de Emergencia 250 kW",
      frequency: "Mensual",
      nextDueDate: "2026-08-27",
      assignedTech: "Téc. Fernando Ruiz",
      estimatedHours: 2.0,
      active: true
    }
  ],
  technicians: [
    { id: "TCH-01", name: "Ing. Carlos Mendoza", role: "Técnico Senior Eléctrico", email: "admin@park.com", phone: "+52 33 1122 3344", activeOrders: 2 },
    { id: "TCH-02", name: "Téc. Roberto Gómez", role: "Especialista HVAC", email: "auditor@park.com", phone: "+52 33 2233 4455", activeOrders: 1 },
    { id: "TCH-03", name: "Ing. Alejandro Silva", role: "Especialista Elevación Otis", email: "alejandro.silva@plataformapark.com", phone: "+52 33 3344 5566", activeOrders: 0 },
    { id: "TCH-04", name: "Téc. Fernando Ruiz", role: "Técnico Electromecánico", email: "fernando.ruiz@plataformapark.com", phone: "+52 33 4455 6677", activeOrders: 1 },
    { id: "TCH-05", name: "Téc. Juan Pérez", role: "Mantenimiento Operativo", email: "tecnico@park.com", phone: "+52 33 3800 3333", activeOrders: 2 }
  ],
  users: [
    {
      id: "u-dev-000",
      fullName: "Ing. Desarrollador & QA",
      email: "dev@park.com",
      phone: "+52 (33) 3800-0001",
      role: "developer",
      department: "Ingeniería & DevOps",
      status: "Activo",
      lastLogin: "2026-09-01 10:00",
      avatarUrl: ""
    },
    {
      id: "u-admin-001",
      fullName: "Ing. Carlos Mendoza",
      email: "admin@park.com",
      phone: "+52 (33) 3800-1111",
      role: "admin",
      department: "Dirección de Mantenimiento",
      status: "Activo",
      lastLogin: "2026-09-01 10:00",
      avatarUrl: ""
    },
    {
      id: "u-supervisor-002",
      fullName: "Arq. Sofía Ramírez",
      email: "supervisor@park.com",
      phone: "+52 (33) 3800-2222",
      role: "supervisor",
      department: "Supervisión de Campo",
      status: "Activo",
      lastLogin: "2026-09-01 09:30",
      avatarUrl: ""
    },
    {
      id: "u-tecnico-003",
      fullName: "Téc. Juan Pérez",
      email: "tecnico@park.com",
      phone: "+52 (33) 3800-3333",
      role: "tecnico",
      department: "Mantenimiento Operativo",
      status: "Activo",
      lastLogin: "2026-09-01 08:45",
      avatarUrl: ""
    },
    {
      id: "u-solicitante-004",
      fullName: "Op. Maria López",
      email: "solicitante@park.com",
      phone: "+52 (33) 3800-4444",
      role: "solicitante",
      department: "Operaciones & Logística",
      status: "Activo",
      lastLogin: "2026-09-01 08:00",
      avatarUrl: ""
    },
    {
      id: "u-auditor-005",
      fullName: "Lic. Roberto Gómez",
      email: "auditor@park.com",
      phone: "+52 (33) 3800-5555",
      role: "auditor",
      department: "Auditoría & Calidad",
      status: "Activo",
      lastLogin: "2026-09-01 07:30",
      avatarUrl: ""
    }
  ]
};

export const STORAGE_KEY = 'PARK_CMMS_DATA_CLEAN_V1';
